### ISSUE TITLE
Error while using uaa-singular to connect a remote UAA server

### ISSUE THREAD

**Issue by Roopali1193** [cloudfoundry/uaa-singular#4]
When the example.html file is configured to communicate with a UAA server running remotely  and a valid OAuth client ID on that server is provided,  we run into the following set of errors : 

1. Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://server_address') does not match the recipient window's origin ('null').

2. Refused to display 'https://server_address/login' in a frame because it set 'X-Frame-Options' to 'DENY'.

What could be the possible causes for this issue ? Need help resolving the same

**Comment by Roopali1193** [comment]
The issue also happens when running the UAA server locally. Can someone let me know if there's any configuration setting required to run the example file?

**Comment by DennisDenuto** [comment]
Thanks for raising this issue.

We have recently published some changes to `uaa-singular` see https://www.npmjs.com/package/uaa-singular which we think should solve both of your issues.

1) There was a bug where we were sending the wrong origin (we were using the uaa domain name instead of the domain of the singular app) when posting a message. This resulted in  `('https://server_address') does not match the recipient window's origin ('null')`

2) We think the `authorize` endpoint (which has also been updated) was redirecting the window iframe to the uaa `login` page instead of returning a 302 with the appropriate hash fragments (which is #error=login_required)

FYI: You can spin up a local uaa server, configured with an example app using uaa-singular by running:
```sh
npm run get-uaa
npm run start-uaa
npm run start-singular-app
```
